set_property IOSTANDARD LVCMOS33 [get_ports {dato1_input[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dato1_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dato1_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dato1_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dato1_input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {posicion[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {posicion[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {posicion[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports display1]
set_property IOSTANDARD LVCMOS33 [get_ports display2]
set_property IOSTANDARD LVCMOS33 [get_ports display3]
set_property IOSTANDARD LVCMOS33 [get_ports display4]
set_property IOSTANDARD LVCMOS33 [get_ports teclaso_guardar]
set_property IOSTANDARD LVCMOS33 [get_ports teclaso_mostrar]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {posicion_IBUF[2]}]

set_property PACKAGE_PIN V15 [get_ports {posicion[2]}]
set_property PACKAGE_PIN W14 [get_ports {posicion[1]}]
set_property PACKAGE_PIN W13 [get_ports {posicion[0]}]
set_property PACKAGE_PIN V7 [get_ports {show_display[4]}]
set_property PACKAGE_PIN U7 [get_ports {show_display[3]}]
set_property PACKAGE_PIN V5 [get_ports {show_display[2]}]
set_property PACKAGE_PIN U5 [get_ports {show_display[1]}]
set_property PACKAGE_PIN V8 [get_ports {show_display[0]}]
set_property PACKAGE_PIN U2 [get_ports display1]
set_property PACKAGE_PIN U4 [get_ports display2]
set_property PACKAGE_PIN V4 [get_ports display3]
set_property PACKAGE_PIN W4 [get_ports display4]
set_property PACKAGE_PIN T18 [get_ports teclaso_guardar]
set_property PACKAGE_PIN U17 [get_ports teclaso_mostrar]

set_property DRIVE 12 [get_ports display1]
set_property PACKAGE_PIN V17 [get_ports {dato1_input[4]}]
set_property PACKAGE_PIN V16 [get_ports {dato1_input[3]}]
set_property PACKAGE_PIN W16 [get_ports {dato1_input[2]}]
set_property PACKAGE_PIN W17 [get_ports {dato1_input[1]}]
set_property PACKAGE_PIN W15 [get_ports {dato1_input[0]}]

set_property PULLDOWN true [get_ports teclaso_guardar]
set_property PULLDOWN true [get_ports teclaso_mostrar]
